"""Add doctor_notes to Appointment model

Revision ID: 61e9d02928ff
Revises: 41ea90e60d5a
Create Date: 2025-12-03 15:58:05.374716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e9d02928ff'
down_revision = '41ea90e60d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_notes', sa.Text(), nullable=True))
        batch_op.alter_column('scheduled_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('scheduled_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('doctor_notes')

    # ### end Alembic commands ###
